server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: root
    password: root
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate


