server:
  port: 8081
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
